### ISSUE TITLE
Python 3.6 Support

### ISSUE THREAD

**Issue by CarlosV89** [ITNG/SurveyGizmo#18]
Hey guys, we were just wondering if there will ever be Python 3.6 support or what is lacking for it to work.

Thank you very much

**Comment by rpkilby** [comment]
Hi @CarlosV89. It looks like the package was already py36 compatible - it just wasn't explicitly tested against it.

**Comment by CarlosV89** [comment]
Yeah I'm getting
```
{'result_ok': False, 'code': 400, 'message': 'Missing / Incorrect Parameters'}
```
on all of my requests, do you know what I'm doing wrong? I tested it on older python versions and it works

```
token =*************************
secret = ************************
sg_client = SurveyGizmo(api_version='v4',
                        api_token=token,
                        api_token_secret=secret)

# Update client options through the config property.
sg_client.config.api_token = token
sg_client.config.api_token_secret = secret
sg_client.api.survey.copy('39501', title='New title boop')
```

**Comment by rpkilby** [comment]
Do you have a stack trace?

**Comment by CarlosV89** [comment]
Not really thats the only error its giving me
```
(ats-venv) ➜  ats-msdynamics DPT-2306-Create-survey-from-existing± python3 sg/run.py
{'result_ok': False, 'code': 400, 'message': 'Missing / Incorrect Parameters'}
```

**Comment by rpkilby** [comment]
Doh - I completely missed the error result you posted. There wouldn't be a stack trace since it's not actually generating an exception. It's just an error response from SG's API. A few thoughts...

- What previous version of python were you using? 
  - If it's 2.7 or prior, this may be a bytes/unicode issue. 
  - If it's an older version of 3.x, try using the `prepare_url` config option. Instead of executing the API request, it simply returns the url & query params. See if there are any tangible differences from when you execute the code on python 3.6 and when you execute it on the earlier version. 
- What version of this package were you using previously?

**Comment by CarlosV89** [comment]
It worked for me in 3.5, the issue arises in 3.6.

Latest version available.

**Comment by rpkilby** [comment]
Last thing I can think of. Try the following (btw, you should only need to pass the token/secret to the constructor. It shouldn't be necessary to directly set it on the config object):

```python 
sg_client = SurveyGizmo(api_version='v4',
                        api_token="*************************",
                        api_token_secret="************************", 
                        prepare_url=True)

url, params = sg_client.api.survey.copy('39501', title='New title boop')

# full request URL
print(requests.get(url, params).url)
```

Try this on both your 3.5 & 3.6 instances. Are there any differences?
