### ISSUE TITLE
Supper nested properties (e.g., email body[html])

### ISSUE THREAD

**Issue by alanpoon** [ITNG/SurveyGizmo#23]
How to use client.api.emailmessage.update to update email's html?

**Comment by rpkilby** [comment]
Hi @alanpoon. Unfortunately, this isn't currently supported. Additional API properties are passed as keyword arugments, and `body[html]` isn't a valid python identifier. To support these kinda of API properties, we'd need to add a `params` argument that is just a standard dictionary. 

A couple of thoughts:
- This dictionary, would automatically support `body[html]`, since the keys are just standard strings.
- We could also expand nested dictionaries. eg, 
  ```python
  params = {
      'options': {'a': 'foo', 'b': 'bar'}
      'c': 'baz',
  }
  ```
  would expand to `options[a]=foo&options[b]=bar&c=baz`

**Comment by rpkilby** [comment]
Hi @alanpoon. I was just getting around to implementing this, when I found out that invalid identifiers may be passed through a kwargs dict.

```python
# invalid
client.api.emailmessage.create(123456, 100000, body[html]="...")

# is valid, apparently
client.api.emailmessage.create(123456, 100000, **{"body[html]": "..."})
```
